### ISSUE TITLE
Issue in Exercise-01 Task-04

### ISSUE THREAD

**Issue by karthikkc24** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#116] opened 2022-02-22 13:41 UTC
In [Exercise-01 Task-04 Step-10](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md)[](https://user-images.githubusercontent.com/83394010/155140796-0d0215df-18d1-4157-b427-0697a12e88b3.png), GitHub action for fabrikam-web.yml workflow is getting failed with the following error.

Error: signing [ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060]: parsing reference: could not parse reference: ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060 main.go:46: error during command execution: signing [ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060]: parsing reference: could not parse reference: ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060

Please find the screenshot below for your reference:

![image](https://user-images.githubusercontent.com/83394010/155143976-5c69f19c-0375-400e-a973-53240619b22a.png)

Instruction in Exercise-01 Task-01 Step-07 is not clear. For REGISTRY, should we use **ghcr.io/${{ github.actor }}** or **ghcr.io/Githubaccountname/Githubreponame**? Please suggest on this.

We have multiple workshops scheduled for this lab. Please check this as soon as possible.

**Comment by DawnmarieDesJardins** [comment] 2022-02-25 20:00
@hatboyzero - Hi Matt!  Any updates for us?

**Comment by hatboyzero** [comment] 2022-02-25 20:13
${{ github.actor }} resolves to the username that initiates the github workflow run.  That part is correct, because you would expect the container registry to be located at `ghcr.io/USERNAME` and the resulting docker image to be pushed to `ghcr.io/USERNAME/IMAGENAME:IMAGETAG`.  In the error above, it looks like you are trying to push to `ghcr.io/USERNAME/REPONAME/IMAGENAME:IMAGETAG`, which is not valid.

**Comment by Karthikkc123** [comment] 2022-02-28 12:03
Hello @hatboyzero, Still facing an issue that workflow got failed with the error failed to solve unexpected status: 403 Forbidden.

**Error: buildx call failed with error: failed to solve: unexpected status: 403 Forbidden**

Please find the screenshots below for your reference:

![image](https://user-images.githubusercontent.com/83394010/155980261-ad63a886-ebf7-4e08-9e3f-e71c8905a6fb.png)

![image](https://user-images.githubusercontent.com/83394010/155980329-c2103117-46e5-4cdf-812b-1647a42b126f.png)

![image](https://user-images.githubusercontent.com/83394010/155978615-0b496546-f8f0-4e16-87d2-390e20bbe43a.png)

**Comment by Karthikkc123** [comment] 2022-02-28 12:03
Hello @hatboyzero, Still facing an issue that workflow got failed with the error failed to solve unexpected status: 403 Forbidden.

**Error: buildx call failed with error: failed to solve: unexpected status: 403 Forbidden**

Please find the screenshots below for your reference:

![image](https://user-images.githubusercontent.com/83394010/155978615-0b496546-f8f0-4e16-87d2-390e20bbe43a.png)

![image](https://user-images.githubusercontent.com/83394010/155980261-ad63a886-ebf7-4e08-9e3f-e71c8905a6fb.png)

![image](https://user-images.githubusercontent.com/83394010/155980329-c2103117-46e5-4cdf-812b-1647a42b126f.png)

**Comment by hatboyzero** [comment] 2022-03-01 02:44
Forgive me for being curious, but what is the difference between the original screenshot and this?  I see in the original screenshot that you are failing at the step to `Sign the published Docker image`, but in the latest screenshot you are failing at the step to `Build and push Docker image` - there is a difference in the workflow YAML between these two screenshots.  I want to know what that difference is.

**Comment by Karthikkc123** [comment] 2022-03-01 05:48
@hatboyzero, please find the details that the changes I have done in the workflow YAML. 

1. In the **env** part updated the **REGISTRY: ghcr.io/${{ github.actor }}** and **IMAGE_NAME: fabrikam-web**

2. In the **Build and push Docker image with Buildx** part added the two lines which mentioned in the labguide.

    **file: ./content-web/Dockerfile**                    
    **context: ./content-web**

**Comment by hatboyzero** [comment] 2022-03-04 15:07
@Karthikkc123 Can you please point me at an existing repository where this problem is manifesting so that I can take a closer look?

**Comment by Karthikkc123** [comment] 2022-03-07 11:53
Hello @hatboyzero, 

[Exercise-1 Task 4: Build Automation with GitHub Registry Step-10](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md), with the latest updates while creating a GitHub action for fabrikam-web.yml workflow is getting failed. Even after following the instructions that to replace the image name in env and file & context in build and push docker as mentioned in the previous comment.

**Comment by hatboyzero** [comment] 2022-03-09 19:12
@Karthikkc123, that is not what I asked for.  Do you have an existing repository up where this behavior is manifesting and reproducible so that I can take a closer look at the issue as it is occurring?

**Comment by Karthikkc123** [comment] 2022-03-14 06:27
@hatboyzero, I don't have that repository.

**Comment by DawnmarieDesJardins** [comment] 2022-03-18 18:34
@Karthikkc123 
Since we are unable to reproduce the error and cannot see your example, closing this issue.

**Comment by hatboyzero** [comment] 2022-03-21 20:59
@Divyasri199 I noticed that the docker repository you are tagging this with has an uppercase character in it's name (likely because your username has an uppercase character).  Could you try the docker image signing operation with everything set to lowercase?

**Comment by Divyasri199** [comment] 2022-03-22 08:33
@hatboyzero, Thanks for the update. The issue has been resolved. Please go ahead with closing the issue.

**Comment by DawnmarieDesJardins** [comment] 2022-03-22 15:41
Thanks team!  Closing the issue as resolved.

**Closed by DawnmarieDesJardins** 2022-03-22 15:41 UTC
